### ISSUE TITLE
Handle conditional grid areas

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/atomic-layout#2]
## What
Need to handle conditional grid areas.

## Why
Consider:

```jsx
const templateMobile = `
  'text'
`

const templateTablet = `
  'text subtext'
`

<Layout
  template={templateMobile}
  templateSm={templateTablet}>
  {({ Text, Subtext }) => (...)}
</Layout>
```

Using this example the `Layout` will throw when trying to render `Subtext` on mobile (`subtext` area is not preset in the template, therefore, its component is not created).

## How
1. Maybe creating an "empty" placeholder component for the areas which are not defined:
```jsx
const Placeholder = () => null
```
2. Maybe analyze each `template` to know the fullest list of areas, and create them all, no matter the screen size.

## Roadmap
- [x] Implement conditional grid areas
- [x] Break down `parseTemplateString` composite function into smaller pure functions
- [x] Write unit tests

**Comment by kettanaito** [comment]
Another idea may be using `MediaQuery` library to wrap the grid area according to its query size (xs, sm, etc.).

**Pros:**
* Solves the conditional rendering on different screen sizes

**Cons:**
* Adds another dependency

**Comment by kettanaito** [comment]
## Update
Conditional grid areas were implemented using `react-responsive`.

Now, whenever conditional area is found, it is being wrapped in `<MediaQuery />` with proper `minWidth` or/and `maxWidth` to match the requested resolution of the area.
